### ISSUE TITLE
MPV and new 2160p_HDR_Rip

### ISSUE THREAD

**Issue by AlFmla** [MartinEesmaa/VVCEasy#42] opened 2024-03-12 22:07 UTC
New builds Win MPV make crash videos and brakes on [new 2160p_HDR_Rip](https://1337x.to/torrent/6014692/Oppenheimer-2023-IMAX-2160p-UHD-HDR-BluRay-VVenC-H-266-VVC-AAC-5-1-RAV1NE/)

The MPV.NET-VVCEasy build from 20_01_2024 and the older ones play the video well, but without HDR.
Can you check and what is the solution for this video to play without crash and brakes and with HDR?

**Comment by MartinEesmaa** [comment] 2024-03-13 22:07
Hi, @AlisaFmla!

That's weird... the new builds Win MPV crashes HDR video when playing using native VVC decoder.
Can you share the log to me please by CLI on your Terminal?

I switched from libvvdec to native VVC decoder to reduce CPU usage after 20/01/2024 build version.

Use CLI as command for any reports, copy and upload the log file over GitHub or my email address:
```
mpv-vvceasy video.mp4 --log-file reportvvchdr.txt
```

Feel free to ask or reply to me.
Meanwhile, I'm gonna check the file that you sent requested link to me to detect errors.

Thank you! :)

- Martin Eesmaa

**Comment by MartinEesmaa** [comment] 2024-03-13 23:29
@AlisaFmla, here are my two screenshots of between 20.01.2024 and latest version of 06.03.2024.

I took screenshot using MPV by pressing "s" key to make sure HDR is on. Tried screenshot format and outputting png file won't show HDR color.

Screenshot of 20.01.2024 version of libvvdec:
https://imgur.com/QUpWj8r

Screenshot of 06.04.2024 version of native VVC decoder:
https://imgur.com/U4VjGgI

I think the solution is I had to switch native VVC decoder to libvvdec by changing code line on my forked repository on Github and then it will be fixed on next build version or might others... but native VVC decoder playing 4K VVC video HDR makes artifacts glitch colors during the movie playing on MPV and FFmpeg.

- Martin Eesmaa

**Comment by AlisaFmla** [comment] 2024-03-14 11:43
[report_vvc_hdr.zip](https://github.com/MartinEesmaa/VVCEasy/files/14601358/report_vvc_hdr.zip)
[left Screenshot of 20.01.2024 version of libvvdec - right Screenshot latest mpv of native VVC decoder](https://imgur.com/a/vSAH6JZ)
left without HDR - right with HDR right?
Does this mean that VVenC version 1.9.1 encoded HDR on this video incorrectly and it cannot be fixed, or with the new versions of native VVC decoder this video will not crash and will be with HDR?
Old versions with libvvdec will not be able on this video to show HDR correctly?

**Comment by MartinEesmaa** [comment] 2024-03-18 10:59
Hi, @AlisaFmla! Thank you for giving your question to me.

> left without HDR - right with HDR true?

On the left version, it may be little washed color so that is without HDR before FFmpeg made patch fix with HDR, I guess. On the right version, it is true HDR color to confirm.

I looked your log file and it seems there are no warnings and errors, but your monitor or laptop screen is 4K input which may slow down without resizing it. On my laptop of using my monitor 1080p, resizes it without issue on mpv, but when I use ffplay then it actually slows video.

I know the problem is native VVC decoder couldn't decode probably **small tiles of 2x1 `--tiles 2x1`** which left there information in description on your sent link. External VVC decoder works fine to decode 2x1 tiles, so we might have to report issue to [ffvvc](https://github.com/ffvvc/FFmpeg) or/and FFmpeg bug report.

RAV1NE encoded using command of vvenc with FFmpeg pipe which causes the decode problem for native VVC decoder on FFmpeg:
ffmpeg -i movie.mkv -f yuv4mpegpipe - | vvencapp --y4m -i - -v 4 --preset medium -q 19 --qpa off --hdr pq_2020 --tiles 2x1 -o 2x1movie.266.

Without tiles command, the both decoder are fine without artificial blocks. Using tiles like 2x1 can only cause problem decoding via artificial blocks with random glitch colors of native VVC decoder on FFmpeg.

Thanks for good spot finding on your sent link. :)

Feel free to ask or reply to me.

Regards
- Martin Eesmaa

**Comment by MartinEesmaa** [comment] 2024-03-18 11:54
@AlisaFmla, I posted issue to ffvvc, now we have to wait to get fixed for updating VVC native decoder codes.

- Martin Eesmaa

**Comment by AlisaFmla** [comment] 2024-03-18 16:37
Thank you for identifying the problem and creating the correct issue. We will wait for the 2x1 tiles decoding solution.
I added a [new one issue](https://github.com/shinchiro/mpv-winbuild-cmake/issues/639) too. So the new ffmpeg and MPV won't play VVC/H.266? You will have to take this into account in new MPV.NET VVCEasy?

**Comment by MartinEesmaa** [comment] 2024-03-19 10:56
Hello, @Andarwinux and @AlFmla.
Thanks for additional comments! :)

@Andarwinux, after I'm reading your comment, I guess I can try and test to see if it's fast to use LLVM and march native.
I might have to install mimalloc and upgrade all my packages on Arch Linux before I go build mpv windows on cmake.

Just going to use CMake build configuration on build folder inside mpv-winbuild-cmake:
```
cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=x86-64-v3 -DCOMPILER_TOOLCHAIN=clang -DLLVM_ENABLE_LTO=Thin ..
ninja llvm
ninja rustup
ninja llvm-clang
ninja mpv
```

You can look my vvdec.cmake: https://github.com/MartinEesmaa/mpv-winbuild-cmake/blob/master/packages/vvdec.cmake
and also CMake more options: https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/CMakeLists.txt

Also for you, @AlFmla. I will follow @Andarwinux's recommendation.
Thank you both! :)

I might start tomorrow or another day after tomorrow to build custom improved MPV build.

Regards
- Martin Eesmaa

**Comment by L4cache** [comment] 2024-03-19 13:42
> It looks like VVCEasy's mpv is built using mpv-winbuild-cmake, if you want to allow ffvvc, just revert [FFmpeg/FFmpeg@110d854](https://github.com/FFmpeg/FFmpeg/commit/110d8549d575aae6b2f627cd63e2eb7082ab8926). By the way, I recommend building vvdec and ffmpeg using the LLVM toolchain with ThinLTO, this dramatically improves the performance of vvdec, for my 7900X, vvdec built with clang -march=native -flto=thin is more than twice as fast as ffvvc.

I don't think it's the compiler optimization that responsible for speed difference. VVdeC has been developed longer thus more mature.



> Hello, @Andarwinux and @AlFmla. Thanks for additional comments! :)
> 
> @Andarwinux, after I'm reading your comment, I guess I can try and test to see if it's fast to use LLVM and march native. I might have to install mimalloc and upgrade all my packages on Arch Linux before I go build mpv windows on cmake.
> 
> Just going to use CMake build configuration on build folder inside mpv-winbuild-cmake:
> 
> ```
> cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=x86-64-v3 -DCOMPILER_TOOLCHAIN=clang -DLLVM_ENABLE_LTO=Thin ..
> ninja llvm
> ninja rustup
> ninja llvm-clang
> ninja mpv
> ```
> 
> You can look my vvdec.cmake: https://github.com/MartinEesmaa/mpv-winbuild-cmake/blob/master/packages/vvdec.cmake and also CMake more options: https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/CMakeLists.txt
> 
> Also for you, @AlFmla. I will follow @Andarwinux's recommendation. Thank you both! :)
> 
> I might start tomorrow or another day after tomorrow to build custom improved MPV build.
> 
> Regards
> 
> * Martin Eesmaa


IIRC, VVdeC did some optimization for "low speed" (e.g. limited to realtime playback) decoding CPU usage recently.

**Comment by MartinEesmaa** [comment] 2024-03-21 07:16
@Andarwinux, thanks for more information to me.
I might start first generic build and then maybe LLVM custom MPV build with your following recommendations and also vvdec flag that you modified.

One thing notice that following CMake flag `-DVVDEC_ENABLE_LINK_TIME_OPT=OFF` means LTO is turned off, cause maybe FFmpeg doesn't detect libvvdec and returns library error undeclared. I hope I can turn back on if it's possible.

Thanks again! :)

Regards
- Martin Eesmaa

**Comment by MartinEesmaa** [comment] 2024-03-21 12:58
Hi @Andarwinux and @AlFmla. Normal build is added, but LLVM build is requested by @Andarwinux is process await to make build times for long hours.

Also @Andarwinux, thanks for giving tip to me. :)

Regards
- Martin Eesmaa

**Comment by MartinEesmaa** [comment] 2024-03-21 22:09
Hi @Andarwinux, your request is finished and I made MPV custom build of x86_64-v3 version.
The two builds of generic and native are finished with libvvdec decoding.

Also @AlFmla, thanks for letting me know for creating your own issue. :)

This issue is solved and closed.

- Martin Eesmaa

**Closed by MartinEesmaa** 2024-03-21 22:09 UTC
